### ISSUE TITLE
API Quota Exceeded

### ISSUE THREAD

**Issue by frkotou** [beveradb/youtube-bulk-upload#11]
I'm getting this after 5 video uploads:

<HttpError 403 when requesting None returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">

**Comment by beveradb** [comment]
https://developers.google.com/youtube/v3/guides/quota_and_compliance_audits
