### ISSUE TITLE
Disable check for duplicate videos don't work

### ISSUE THREAD

**Issue by frkotou** [beveradb/youtube-bulk-upload#12]
![scr](https://github.com/user-attachments/assets/ba59a7ce-17a8-401b-acf1-f9941449eae1)
[youtube_bulk_upload.log](https://github.com/user-attachments/files/18169509/youtube_bulk_upload.log)

**Comment by beveradb** [comment]
Sorry about that; fixed in `v0.5.1`
https://github.com/beveradb/youtube-bulk-upload/releases/tag/v0.5.1

(I also added a reset youtube auth button in case that helps)

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/7f8120a8-5348-4cab-91a6-025c7ac4999a" />

**Comment by frkotou** [comment]
Thank you, it works correctly now.
