### ISSUE TITLE
ERROR - gui - An error occurred during upload: unsupported operand type(s) for 'in': 'str' and 'EnumType'

### ISSUE THREAD

**Issue by LovelyCupOfTea** [beveradb/youtube-bulk-upload#4]
Hi There Andrew! 

Receiving the following error when running the first Dry run after connecting the Json file 

ERROR - gui - An error occurred during upload: unsupported operand type(s) for 'in': 'str' and 'EnumType'

Many thanks

**Comment by beveradb** [comment]
Never encountered that one but based on it being a Python syntax error I would guess you're probably using a very old version of Python. This project requires Python 3.9 or newer.

If you manage to figure out the issue, please consider raising a Pull Request to improve the docs for future users 😄

**Comment by emourdavid** [comment]
I have same issue when Run with Dry Run checkbox

**Comment by widardd** [comment]
Same here, Python 3.10.7

**Comment by beveradb** [comment]
Hey @emourdavid and @widardd, sorry to hear you're having issues with it - could you provide any further detail on your systems? e.g. what operating system, how did you install Python, how did you install `youtube-bulk-upload`, etc?

**Comment by gauravr397** [comment]
Same issue here , tried GUI on 2 machines 
OS - Windows 10
Python - 3.12.6
Python - 3.11.4

**Comment by emourdavid** [comment]
Install by using file exe on Win10, python 3.10.11

**Comment by gauravr397** [comment]
@emourdavid 
No luck still same with python 3.10.11

**Comment by beveradb** [comment]
Hey folks, please give the latest release (`0.4.1`) a try - I'm hoping [this commit](https://github.com/beveradb/youtube-bulk-upload/commit/9dff4ff89006c6a7a0208bddec3c1e5d02dc727a) will have fixed the issue (though I wasn't able to easily reproduce on my mac).

**Comment by beveradb** [comment]
Since I never heard back from y'all, I'm going to optimistically assume this fixed it 😄
