### ISSUE TITLE
Disable the video similarity feature

### ISSUE THREAD

**Issue by frkotou** [beveradb/youtube-bulk-upload#7]
Hi, I always upload the same video titles, only with a different date. Unfortunately, this prevents me from uploading videos in non-interactive mode and it always rejects them due to similarity. Is there a way to disable the similarity feature? I would like to upload, for example, 15 2-hour videos without waiting for another question in interactive mode, if the video is the same as another, but let it run by itself.

**Comment by beveradb** [comment]
Yeah that ought to be a parameter really, you can just comment out this line:
https://github.com/beveradb/youtube-bulk-upload/blob/9dff4ff89006c6a7a0208bddec3c1e5d02dc727a/youtube_bulk_upload/bulk_upload.py#L455

If you want it to be a GUI parameter, PRs are welcome!

**Comment by frkotou** [comment]
Thank you, how do I do it on the GUI? (I'm using the exe on Windows).

**Comment by beveradb** [comment]
You'd need to modify the code - free to submit a PR with a fix!

I don't have any personal motivation to work on this project but will merge PRs/release if others want to keep developing it :)

**Comment by beveradb** [comment]
Implemented in v0.5:
https://github.com/beveradb/youtube-bulk-upload/releases/tag/v0.5.0

<img width="1112" alt="YouTube Bulk Upload - v0 5 0 2024-12-16 17-43-32" src="https://github.com/user-attachments/assets/3e70b122-e56b-4e92-9ec2-7fb885c539fd" />
