### ISSUE TITLE
.mkv file not detected

### ISSUE THREAD

**Issue by Judeisbad** [beveradb/youtube-bulk-upload#8]
I've edited the Input File Extensions field to ".mp4 .mov .mkv .flv", but .mkv files in the directory aren't getting detected.

**Comment by beveradb** [comment]
Feel free to submit a PR with a fix!

I don't have any personal motivation to work on this project but will merge PRs/release if others want to keep developing it :)

**Comment by beveradb** [comment]
This should now be resolved in version 0.5 onwards:
https://github.com/beveradb/youtube-bulk-upload/releases/tag/v0.5.0
