### ISSUE TITLE
A way to choose a different youtube account under same email address

### ISSUE THREAD

**Issue by Judeisbad** [beveradb/youtube-bulk-upload#9]
I have 3 Youtube Accounts under the same email address.

Is there a way to choose which youtube account I am uploading to, or is it not possible?

**Comment by beveradb** [comment]
I would expect that when you first authenticate through your web browser it'll ask you which account, but I can't remember tbh. If an improvement to the code would help with this, feel free to submit a PR!

I don't have any personal motivation to work on this project but will merge PRs/release if others want to keep developing it :)

**Comment by beveradb** [comment]
This should now be solved in version `0.5.1` with the new "Reset YouTube Auth" button (which just deletes the auth token created when you log in).

So, let's say you need to bulk upload some videos to one YouTube channel and then some other videos to a different channel, you can just click the button to reset your auth after the first set of videos are uploaded, and when you click `Run` again it'll open your browser to repeat the YouTube authentication flow, during which you can select a different channel.

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/3efd3033-eeca-4ca4-a75d-ffbfcaeb72be" />
